name: Deploy web to GitHub Pages

on:
  push:
    branches:
      - main  # Runs when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web  # Publishes the contents of the web folder
          publish_branch: gh-pages